export const styles = {
  dashboardContainer: {
    padding: '24px',
    width: '100%',
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    maxWidth: 'none',
    margin: 0,
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '20px 24px',
    marginBottom: '24px',
    background: 'rgba(18, 18, 30, 0.45)',
  },
  headerTitle: {
    fontSize: '1.6rem',
    fontWeight: '700',
    color: '#fff',
    margin: 0,
  },
  headerSubtitle: {
    fontSize: '0.82rem',
    color: '#94a3b8',
    marginTop: '4px',
  },
  roleTag: {
    marginLeft: '6px',
    padding: '2px 8px',
    borderRadius: '4px',
    fontSize: '0.7rem',
    fontWeight: '700',
    textTransform: 'uppercase',
    border: '1px solid',
  },
  headerActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  healthMiniBadge: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '6px 12px',
    borderRadius: '8px',
    background: 'rgba(0,0,0,0.15)',
    border: '1px solid rgba(255,255,255,0.04)',
  },
  iconBtn: {
    padding: '10px',
    borderRadius: '8px',
  },
  logoutBtn: {
    padding: '10px 16px',
    background: 'rgba(239, 68, 68, 0.1)',
    borderColor: 'rgba(239, 68, 68, 0.2)',
    color: '#f87171',
    ':hover': {
      background: 'rgba(239, 68, 68, 0.2)',
      color: '#fff',
    }
  },
  metricsBar: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(230px, 1fr))',
    gap: '16px',
    marginBottom: '24px',
  },
  metricCard: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    padding: '16px 20px',
    background: 'rgba(18, 18, 30, 0.35)',
  },
  metricIconBox: {
    display: 'flex',
    padding: '10px',
    borderRadius: '10px',
    background: 'rgba(255,255,255,0.05)',
  },
  metricVal: {
    fontSize: '1.35rem',
    fontWeight: '700',
    color: '#fff',
    lineHeight: '1.2',
  },
  metricLabel: {
    fontSize: '0.75rem',
    color: '#64748b',
    marginTop: '2px',
    fontWeight: '500',
  },
  sidebar: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    padding: '16px',
    background: 'rgba(18, 18, 30, 0.35)',
  },
  sidebarBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    width: '100%',
    padding: '12px 16px',
    borderRadius: '8px',
    border: 'none',
    background: 'transparent',
    color: '#94a3b8',
    fontSize: '0.88rem',
    fontWeight: '500',
    cursor: 'pointer',
    textAlign: 'left',
    transition: 'all 0.2s',
  },
  sidebarBtnActive: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    width: '100%',
    padding: '12px 16px',
    borderRadius: '8px',
    border: 'none',
    background: 'rgba(168, 85, 247, 0.12)',
    color: '#d8b4fe',
    fontSize: '0.88rem',
    fontWeight: '600',
    cursor: 'pointer',
    textAlign: 'left',
    boxShadow: 'inset 0 0 0 1px rgba(168, 85, 247, 0.25)',
  },
  mainPanel: {
    padding: '24px',
    minHeight: '600px',
    background: 'rgba(18, 18, 30, 0.45)',
  },
  tabHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottom: '1px solid rgba(255,255,255,0.06)',
    paddingBottom: '16px',
    marginBottom: '20px',
  },
  tabTitle: {
    fontSize: '1.25rem',
    fontWeight: '600',
    color: '#fff',
    margin: 0,
    fontFamily: 'Outfit',
  },
  tabSubtitle: {
    fontSize: '0.82rem',
    color: '#64748b',
    marginTop: '4px',
  },
  inlineForm: {
    background: 'rgba(0,0,0,0.15)',
    border: '1px solid rgba(255,255,255,0.04)',
    borderRadius: '12px',
    padding: '20px',
    marginBottom: '24px',
  },
  formTitle: {
    fontSize: '1rem',
    fontWeight: '600',
    color: '#fff',
    marginBottom: '16px',
    fontFamily: 'Outfit',
  },
  formGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
    gap: '16px',
  },
  formLabel: {
    display: 'block',
    fontSize: '0.75rem',
    fontWeight: '600',
    textTransform: 'uppercase',
    color: '#64748b',
    marginBottom: '6px',
    letterSpacing: '0.02em',
  },
  checkboxWrapper: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginTop: '28px',
  },
  checkboxInput: {
    width: '16px',
    height: '16px',
    cursor: 'pointer',
  },
  checkboxLabel: {
    fontSize: '0.88rem',
    color: '#94a3b8',
    cursor: 'pointer',
  },
  formActions: {
    display: 'flex',
    gap: '12px',
    marginTop: '20px',
    justifyContent: 'flex-end',
  },
  filterRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '16px',
    marginBottom: '16px',
    flexWrap: 'wrap',
  },
  filterGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  searchInput: {
    width: '240px',
  },
  filterSelect: {
    width: '150px',
  },
  sortLabel: {
    fontSize: '0.8rem',
    color: '#64748b',
  },
  sortOrderBtn: {
    padding: '9px 12px',
    fontSize: '0.75rem',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    textAlign: 'left',
  },
  th: {
    padding: '12px 16px',
    borderBottom: '2px solid rgba(255,255,255,0.06)',
    color: '#64748b',
    fontSize: '0.75rem',
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: '0.02em',
  },
  tr: {
    borderBottom: '1px solid rgba(255,255,255,0.04)',
    transition: 'background 0.2s',
    ':hover': {
      background: 'rgba(255,255,255,0.01)',
    }
  },
  td: {
    padding: '14px 16px',
    fontSize: '0.88rem',
    color: '#e2e8f0',
  },
  miniTag: {
    fontSize: '0.65rem',
    background: 'rgba(255,255,255,0.04)',
    border: '1px solid rgba(255,255,255,0.06)',
    padding: '2px 6px',
    borderRadius: '4px',
    color: '#94a3b8',
  },
  modelsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
    gap: '16px',
  },
  modelCard: {
    padding: '20px',
    background: 'rgba(18, 18, 30, 0.35)',
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
  },
  modelCardHeader: {
    display: 'flex',
    gap: '12px',
    alignItems: 'center',
  },
  modelIconBox: {
    display: 'flex',
    padding: '8px',
    borderRadius: '8px',
    background: 'rgba(168, 85, 247, 0.08)',
    border: '1px solid rgba(168, 85, 247, 0.15)',
  },
  modelTitle: {
    fontSize: '0.95rem',
    fontWeight: '600',
    color: '#fff',
    margin: 0,
  },
  modelCode: {
    fontSize: '0.72rem',
    color: '#64748b',
  },
  modelCardBody: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    borderTop: '1px solid rgba(255,255,255,0.04)',
    paddingTop: '12px',
  },
  selectStyle: {
    appearance: 'none',
    background: 'rgba(0,0,0,0.25)',
  },
  mappingsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  mappingRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '16px 20px',
    background: 'rgba(18, 18, 30, 0.35)',
    gap: '20px',
    flexWrap: 'wrap',
  },
  mappingEntity: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  chartGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))',
    gap: '20px',
  },
  chartCard: {
    padding: '24px',
    background: 'rgba(18, 18, 30, 0.35)',
  },
  chartTitle: {
    fontSize: '1rem',
    fontWeight: '600',
    color: '#fff',
    marginBottom: '20px',
    fontFamily: 'Outfit',
  },
  barList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  barRow: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  barLabel: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '0.8rem',
    color: '#94a3b8',
  },
  barOuter: {
    height: '6px',
    width: '100%',
    background: 'rgba(0,0,0,0.2)',
    borderRadius: '3px',
    overflow: 'hidden',
  },
  barInner: {
    height: '100%',
    borderRadius: '3px',
  },
  logModel: {
    fontSize: '0.75rem',
    background: 'rgba(59,130,246,0.1)',
    color: '#93c5fd',
    padding: '2px 8px',
    borderRadius: '4px',
    fontFamily: 'monospace',
    border: '1px solid rgba(59,130,246,0.15)',
  },
  guideContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
    marginTop: '16px',
  },
  floatingAlertError: {
    position: 'fixed',
    top: '20px',
    right: '20px',
    background: '#ef4444',
    color: '#fff',
    padding: '12px 24px',
    borderRadius: '8px',
    boxShadow: '0 8px 30px rgba(239, 68, 68, 0.25)',
    zIndex: 9999,
    fontSize: '0.9rem',
    fontWeight: '600',
  },
  floatingAlertSuccess: {
    position: 'fixed',
    top: '20px',
    right: '20px',
    background: '#10b981',
    color: '#fff',
    padding: '12px 24px',
    borderRadius: '8px',
    boxShadow: '0 8px 30px rgba(16, 185, 129, 0.25)',
    zIndex: 9999,
    fontSize: '0.9rem',
    fontWeight: '600',
  },
  metaResponseGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(130px, 1fr))',
    gap: '16px',
    background: 'rgba(0,0,0,0.15)',
    padding: '16px',
    borderRadius: '8px',
    border: '1px solid rgba(255, 255, 255, 0.04)',
  },
  metaLabel: {
    fontSize: '0.65rem',
    color: '#64748b',
    textTransform: 'uppercase',
    fontWeight: '700',
    letterSpacing: '0.02em',
    display: 'block',
  },
  metaVal: {
    fontSize: '0.88rem',
    fontWeight: '600',
    color: '#fff',
    marginTop: '2px',
  },
  responseTextBlock: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  responseTextTitle: {
    fontSize: '0.8rem',
    color: '#94a3b8',
    fontWeight: '600',
  },
  responseTextPre: {
    padding: '12px',
    borderRadius: '8px',
    border: '1px solid rgba(255,255,255,0.05)',
    background: 'rgba(0,0,0,0.25)',
    color: '#e2e8f0',
    fontSize: '0.8rem',
    overflowY: 'auto',
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-all',
    fontFamily: 'monospace',
  },
};
